import path from 'path';
import { test, expect } from '@playwright/test';

import * as dotenv from 'dotenv';
const env_path = path.join(process.cwd(), '../' , `.env${process.env.ENV === 'LOCAL' ? '.local' : ''}`);
console.log(`env_path=${env_path}`);
dotenv.config({path: env_path});
const DINER_URL = process.env.DINER_URL;
const DINER_GOOGLE_USR = process.env.DINER_GOOGLE_USR || 'XX';
const DINER_GOOGLE_PWD = process.env.DINER_GOOGLE_PWD || 'XX';
console.log(DINER_GOOGLE_PWD);
test.use({ javaScriptEnabled: true });

test('diner login', async ({ page }) => {
  await page.goto('http://localhost:3000/?token=LOCAL_TABLE11_STORE2');
  await page.locator('div').filter({ hasText: /^Continue With Google$/ }).first().click();
  await page.getByLabel('Email or phone').click();
  await page.getByLabel('Email or phone').fill(DINER_GOOGLE_USR);
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Enter your password').click();
  await page.getByLabel('Enter your password').fill(DINER_GOOGLE_PWD);
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#event_menu_1').getByRole('img').click();
  await page.getByRole('button', { name: '₩5,000 Add to tab' }).click();
  await page.getByRole('button', { name: '1 Order' }).click();
  await page.locator('div').filter({ hasText: /^Pay Mine/ }).first().click();
  await page.getByRole('button', { name: 'Checkout' }).isEnabled();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('radio', { name: 'web_pay' }).isVisible();
  await page.getByRole('radio', { name: 'web_pay' }).check();
  await page.getByRole('button', { name: 'Pay ₩5,000' }).click();
  await page.getByRole('link', { name: '모두 동의 체크' }).click();
  await page.getByRole('link', { name: 'Select' }).click();
  await page.locator('span').filter({ hasText: 'LOTTE' }).nth(1).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.frameLocator('iframe[name="certframe"]').getByRole('link', { name: '다른 결제' }).click();
  await page.frameLocator('iframe[name="certframe"]').getByRole('button', { name: '일반 결제 카드번호 결제' }).click();
  await page.frameLocator('iframe[name="certframe"]').getByRole('textbox', { name: '카드번호 첫번째 네자리 수를 입력해주세요.' }).click();
  await page.frameLocator('iframe[name="certframe"]').getByRole('textbox', { name: '카드번호 첫번째 네자리 수를 입력해주세요.' }).fill('5105');
  await page.frameLocator('iframe[name="certframe"]').getByRole('textbox', { name: '카드번호 두번째 네자리 수를 입력해주세요.' }).fill('5450');
  await page.frameLocator('iframe[name="certframe"]').getByRole('textbox', { name: '카드번호 세번째 네자리 수를 입력해주세요.' }).fill('0062');
  await page.frameLocator('iframe[name="certframe"]').getByRole('textbox', { name: '카드번호 세번째 네자리 수를 입력해주세요.' }).press('Tab');
  await page.frameLocator('iframe[name="certframe"]').getByRole('textbox', { name: '카드번호 네번째 네자리 수를 입력해주세요.' }).click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_cdNo4_Row1 > div:nth-child(2)').click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_cdNo4_Row0 > div:nth-child(4)').click();
  await page.frameLocator('iframe[name="certframe"]').locator('.transkey_key').first().click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_cdNo4_Row0 > div:nth-child(3)').click();
  await page.frameLocator('iframe[name="certframe"]').locator('input[name="cvcV"]').click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_cvcV_Row0 > div:nth-child(3)').click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_cvcV_Row0 > div').first().click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_cvcV_Row1 > div:nth-child(5)').click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_cvcV_Row2 div').nth(2).click();
  await page.frameLocator('iframe[name="certframe"]').getByRole('link', { name: '확인' }).click();
  await page.frameLocator('iframe[name="certframe"]').locator('#acsPswd').click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_acsPswd_Row2 > div:nth-child(2)').click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_acsPswd_Row1 > div:nth-child(8)').click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_acsPswd_Row3 > div:nth-child(5)').click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_acsPswd_Row1 > div:nth-child(10)').click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_acsPswd_Row2 > div').first().click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_acsPswd_Row3 > div:nth-child(9)').click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_acsPswd_Row2 > div').first().click();
  await page.frameLocator('iframe[name="certframe"]').locator('div:nth-child(5)').first().click();
  await page.frameLocator('iframe[name="certframe"]').locator('div:nth-child(5)').first().click();
  await page.frameLocator('iframe[name="certframe"]').locator('#mtk_acsPswd_Row4 div').nth(2).click();
  await page.frameLocator('iframe[name="certframe"]').getByRole('link', { name: '확인' }).click();
  await page.getByRole('link', { name: '결제 정보 확인 체크' }).click();
  await page.getByRole('button', { name: 'Finish' }).click();
  await page.goto('http://localhost:3000/customer-receipt?resultCode=0000&status=approvement');
  await page.goto('http://localhost:3000/customer-receipt');
});
